export const JAIL_PRICE = 50;
export const SPEEDING_DOUBLES = 3;
export const TURNS_IN_JAIL = 3;
export const COMMUNITY_SERVICE_PAYMENT = 20;
export const PLAYER_COLORS = ["green", "red", "yellow", "blue"];
export const MINIGAME_PAGES = ['/DinoGame', '/WhackAMole', '/GuitarHero'];
export const AI_GO_BONUS = 200;
export const MAX_HOUSES = 5;
export const RICH_HELP_POOR_AMOUNT = 100;